[package]
name = "llmserver-rs"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
#rkllm-rs = { path = "../../rkllm-rs"}

[dependencies]
utoipa = { version = "5.3.1", features = [ "actix_extras" ] }
actix-web = "4.10.2"
serde = { version = "1.0.219", features = ["derive"] }
redis = { version = "0.29.1", features = ["tokio-comp"] }
actix-service = "2.0.3"
futures = "0.3.31"
tokio = "1.44.0"
utoipa-actix-web = "0.1.2"
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"] }
serde_json = "1.0.140"
env_logger = "0.11.7"
rkllm-rs = "0.1.6"
autotokenizer = "0.1.1"
serde_variant = "0.1.3"
actix = "0.13.5"
tokio-stream = "0.1.17"
rand = "0.9.0"
hf-hub = "0.4.2"
clap = "4.5.32"
